### ISSUE TITLE
Error occurs when `afx install`

### ISSUE THREAD

**Issue by jshin** [b4b4r07/afx#38]
## WHY
When executing `afx install`, panic occurs with the following error message and the installation fails.

```
$ afx install
? OK to install these packages? zsh-users/zsh-completions, zsh-users/zsh-autosuggestions, zdharma-continuum/fast-syntax-highlighting, ... (5 packages) Yes
✔ b4b4r07/enhancd
panic: assignment to entry in nil maprs/zsh-autosuggestions, zdharma-continuum/fast-syntax-highl...

goroutine 83 [running]:
github.com/b4b4r07/afx/pkg/state.add(...)
        /home/jshin/go/pkg/mod/github.com/b4b4r07/afx@v0.1.19/pkg/state/state.go:122
github.com/b4b4r07/afx/pkg/state.(*State).Add(0xc00038c140?, {0x7f96d535bf98?, 0xc00013ecf0?})
        /home/jshin/go/pkg/mod/github.com/b4b4r07/afx@v0.1.19/pkg/state/state.go:287 +0x1b3
github.com/b4b4r07/afx/cmd.(*installCmd).run.func2()
        /home/jshin/go/pkg/mod/github.com/b4b4r07/afx@v0.1.19/cmd/install.go:120 +0x1c5
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /home/jshin/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/jshin/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d
```

## Environment
OS : Ubuntu 20.04.4
Go : 1.18
afx version : [v0.1.19](https://github.com/b4b4r07/afx/releases/tag/v0.1.19)
yaml file
```yaml
github:
  - name: zsh-users/zsh-completions
    owner: zsh-users
    repo: zsh-completions
    plugin:
      sources:
        - zsh-completions.plugin.zsh
  - name: zsh-users/zsh-autosuggestions
    owner: zsh-users
    repo: zsh-autosuggestions
    plugin:
      sources:
        - zsh-completions.plugin.zsh
  - name: zdharma-continuum/fast-syntax-highlighting
    owner: zdharma-continuum
    repo: fast-syntax-highlighting
    plugin:
      sources:
        - fast-syntax-highlighting.plugin.zsh
  - name: b4b4r07/enhancd
    owner: b4b4r07
    repo: enhancd
    plugin:
      sources:
        - init.sh
      env:
        ENHANCD_DISABLE_HOME: 1
  - name: tmux-plugins/tpm
    owner: tmux-plugins
    repo: tpm
    command:
      link:
      - from: .
        to: $HOME/.tmux/plugins/tpm
```
