### ISSUE TITLE
Add release.format option

### ISSUE THREAD

**Issue by 4513ECHO** [b4b4r07/afx#45]
## WHAT

(Write what you need)

How about add `release.format` option like that of
[aqua](https://aquaproj.github.io/docs/reference/registry-config#packages-common-attributes), a project very similar to afx?

```diff
 github:
   - name: high-moctane/mocword-data
     description: Predict next words.
     owner: high-moctane
     repo: mocword-data
     release:
       name: mocword.sqlite.gz
       tag: eng20200217
+      format: gz
     command:
       env:
         MOCWORD_DATA: $XDG_CACHE_HOME/mocword/mocword.sqlite
       link:
         - from: mocword.sqlite
           to: $XDG_CACHE_HOME/mocword/mocword.sqlite
```

## WHY

(Write the background of this issue)

Currently afx detects the format of archives
[by extention](https://github.com/b4b4r07/afx/blob/adb5a3e57e4517452b514f2b22eedc3bb83382d5/pkg/github/github.go#L277).
However it is failed when the name of release has dot like below.

```yaml
github:
  - name: high-moctane/mocword-data
    description: Predict next words.
    owner: high-moctane
    repo: mocword-data
    release:
      name: mocword.sqlite.gz
      tag: eng20200217
    command:
      env:
        MOCWORD_DATA: $XDG_CACHE_HOME/mocword/mocword.sqlite
      link:
        - from: mocword.sqlite
          to: $XDG_CACHE_HOME/mocword/mocword.sqlite
```
