### ISSUE TITLE
Add build.cwd option

### ISSUE THREAD

**Issue by 4513ECHO** [b4b4r07/afx#46]
## WHAT

(Write what you need)

How about add `build.cwd` option to change cwd during building?

```yaml
- name: nkf
  description: Netword Kanji Filter
  url: https://free.nchc.org.tw/osdn//nkf/70406/nkf-2.1.5.tar.gz
  command:
    build:
      cwd: nkf-2.1.5
      steps:
        - make
        - make install prefix=~/.local
    link:
      - from: nkf
```

## WHY

(Write the background of this issue)

Sometimes `build.steps` requires changing cwd, but `cd` command is not working.

```yaml
- name: nkf
  description: Netword Kanji Filter
  url: https://free.nchc.org.tw/osdn//nkf/70406/nkf-2.1.5.tar.gz
  command:
    build:
      steps:
        - cd nkf-2.1.5 # not working
        - make
        - make install prefix=~/.local
    link:
      - from: nkf
```
