### ISSUE TITLE
[Bug Report] Update error

### ISSUE THREAD

**Issue by uga-rosa** [b4b4r07/afx#52]
## WHAT

When updating a package that is already installed, there is an error that appears to be a problem with the timing of removing the past. When this happens, it is inconvenient because it requires re-entry of GITHUB_TOKEN.

```sh
❯ afx update
? OK to update these packages? cli/cli Yes
✖ cli/cli
[ERROR]: 1 error occurred:
        * 1 error occurred:
                * cli/cli: failed to get command.link: cli/cli: 2 files matched: []string{"/home/uga/.afx/github.com/cli/cli/gh_2.14.6_linux_amd64/bin/gh", "/home/uga/.afx/github.com/cli/cli/gh_2.14.4_linux_amd64/bin/gh"}
```

Here is an excerpt from my release.yaml.
```yaml
- github:
  - name: cli/cli
    description: Github's official command line tool
    owner: cli
    repo: cli
    release:
      name: gh
      tag: v2.14.6
      asset:
        filename: '{{ .Release.Name }}_{{ replace .Release.Tag "v" "" }}_{{ .OS }}_{{ .Arch }}.tar.gz'
    command:
      link:
        - from: '**/gh'
```

## WHY

Bug report.
