### ISSUE TITLE
Behavior of "afx uninstall" on local

### ISSUE THREAD

**Issue by shihanng** [b4b4r07/afx#53]
## WHAT

Given the configuration below using `local`. 

```yml
local:
- name: zsh
  description: My zsh scripts
  directory: ~/test
  plugin:
    sources:
    - '[0-9]*.zsh'
```

After we remove the above and execute `afx uninstall`, it seems that `afx` will delete the `~/test` directory.

```
2023/01/25 17:12:19 [DEBUG] zsh: removed from state
deleted /Users/shi.han.ng/test
```

I wonder if this is the intended behavior?

## WHY

Since afx does not install/create `~/test` but only uses it as source. I find it surprising that `afx` deleting the directory that it does not manage.
